"use client";

import React, { useState } from "react";

interface ConsoleProps {
  generatedHtml: string | null;
  generatedPython: string | null;
  onRunPython: (code: string) => Promise<string>;
}

export const Console: React.FC<ConsoleProps> = ({
  generatedHtml,
  generatedPython,
  onRunPython,
}) => {
  const [activeTab, setActiveTab] = useState<"preview" | "console">("preview");
  const [pythonCode, setPythonCode] = useState("");
  const [terminalOutput, setTerminalOutput] = useState("");
  const [running, setRunning] = useState(false);

  // Sync state when props change
  React.useEffect(() => {
    if (generatedPython) {
      setPythonCode(generatedPython);
    }
  }, [generatedPython]);

  const handleRunCode = async () => {
    if (!pythonCode.trim()) return;
    setRunning(true);
    setTerminalOutput("Connecting to Colab VM Sandbox...\nInitializing execution context...\nRunning Python sandbox...\n");
    try {
      const result = await onRunPython(pythonCode);
      setTerminalOutput((prev) => prev + result);
    } catch (err: any) {
      setTerminalOutput((prev) => prev + `[VM ERROR] Failed to execute: ${err?.message || err}`);
    } finally {
      setRunning(false);
    }
  };

  return (
    <div className="glass rounded-xl flex flex-col h-[650px]">
      {/* Tabs Header */}
      <div className="flex items-center justify-between border-b border-zinc-800 bg-zinc-900/40 px-4 rounded-t-xl">
        <div className="flex gap-4">
          <button
            onClick={() => setActiveTab("preview")}
            className={`py-3 text-xs uppercase tracking-wider font-semibold border-b-2 transition-all ${
              activeTab === "preview"
                ? "border-indigo-500 text-white font-bold"
                : "border-transparent text-zinc-400 hover:text-zinc-200"
            }`}
          >
            🌐 Live Web Preview
          </button>
          <button
            onClick={() => setActiveTab("console")}
            className={`py-3 text-xs uppercase tracking-wider font-semibold border-b-2 transition-all ${
              activeTab === "console"
                ? "border-indigo-500 text-white font-bold"
                : "border-transparent text-zinc-400 hover:text-zinc-200"
            }`}
          >
            💻 Colab VM Console
          </button>
        </div>
        <span className="text-[10px] text-zinc-500 font-mono">Twin Engine Output</span>
      </div>

      {/* Content area */}
      <div className="flex-1 p-4 bg-zinc-950/40 relative">
        {activeTab === "preview" ? (
          generatedHtml ? (
            <iframe
              title="live-preview"
              srcDoc={generatedHtml}
              className="w-full h-full border border-zinc-800 rounded-lg bg-white"
              sandbox="allow-scripts"
            />
          ) : (
            <div className="flex flex-col items-center justify-center h-full text-zinc-500 gap-2">
              <span className="text-3xl">🌐</span>
              <p className="text-sm">Web application UI generated by the swarm will render here.</p>
            </div>
          )
        ) : (
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4 h-full">
            {/* Editor */}
            <div className="flex flex-col h-full border border-zinc-850 bg-zinc-950 p-3 rounded-lg">
              <div className="flex items-center justify-between mb-2 pb-2 border-b border-zinc-900">
                <span className="text-[11px] font-bold text-zinc-400 font-mono">source_code.py</span>
                <button
                  onClick={handleRunCode}
                  disabled={running}
                  className="bg-indigo-600 hover:bg-indigo-500 text-white text-[10px] uppercase font-bold tracking-wider px-3 py-1 rounded transition-colors disabled:opacity-50"
                >
                  {running ? "Executing..." : "▶ Execute Code"}
                </button>
              </div>
              <textarea
                value={pythonCode}
                onChange={(e) => setPythonCode(e.target.value)}
                placeholder="# Python source code generated by the Builder node will appear here..."
                className="flex-1 w-full bg-transparent text-xs text-zinc-300 font-mono resize-none focus:outline-none leading-relaxed"
              />
            </div>

            {/* Terminal output */}
            <div className="flex flex-col h-full border border-zinc-850 bg-zinc-950 p-3 rounded-lg">
              <div className="mb-2 pb-2 border-b border-zinc-900 flex justify-between items-center">
                <span className="text-[11px] font-bold text-zinc-400 font-mono">stdout / stderr</span>
                {terminalOutput && (
                  <button
                    onClick={() => setTerminalOutput("")}
                    className="text-[9px] text-zinc-500 hover:text-zinc-300"
                  >
                    [Clear]
                  </button>
                )}
              </div>
              <pre className="flex-1 w-full bg-black/35 rounded text-[10px] text-emerald-400 font-mono p-2 overflow-y-auto leading-relaxed whitespace-pre-wrap">
                {terminalOutput || "# Terminal outputs from the sandboxed VM session will display here..."}
              </pre>
            </div>
          </div>
        )}
      </div>
    </div>
  );
};
